version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ticketDatabase
      MYSQL_USER: dev1
      MYSQL_PASSWORD: ticket1!@
    volumes:
      - mysql_data:/var/lib/mysql

  ticket-booking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_booking_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ticketDatabase
      SPRING_DATASOURCE_USERNAME: dev1
      SPRING_DATASOURCE_PASSWORD: ticket1!@

  jenkins:
    image: jenkins/jenkins:lts  
    container_name: jenkins_server
    ports:
      - "8081:8080"  
    volumes:
      - jenkins_data:/var/jenkins_home 
    depends_on:
      - mysql  

  
volumes:
  mysql_data:
  jenkins_data:
